language: go
sudo: false

matrix:
  include:
    - go: 1.4
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: 1.8
    - go: 1.8
    - go: tip
  allow_failures:
    - go: tip

script:
  - go test -v ./... -bench=./...

