apiVersion: v1
kind: Service
metadata:
  name: api-passgen
spec:
  ports:
    - name: http
      port: 80          # port exposed by Service
      targetPort: 8080  # port exposed by Pod (Dockerfile)
      protocol: TCP
  selector:
    name: api-passgen-pods