#minimum acceptable settings
[default]
min_length = 8
min_special_characters = 2
min_digits = 2
min_lowercase = 1
min_uppercase = 1
results = 1

[strong]
min_length = 16
min_special_characters = 4
min_digits = 4
min_lowercase = 2
min_uppercase = 2
results = 1